config/routes.rb
Rails.application.routes.draw do
  devise_for :admins, :path_names => {:sign_in => 'login', :sign_out => 'logout'}
  devise_for :customers, :path_names => {:sign_in => 'login', :sign_out => 'logout'}

  resources :bicycles
  

  resources :bicycles do
    resources :repairs
  end

  namespace :admin do
    resources :repairs
  end  

  root 'bicycles#index'

end

app/models/admin.rb
class Admin < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/bicycle.rb
class Bicycle < ActiveRecord::Base
  belongs_to :customer
  has_many :repairs
end

app/models/customer.rb
class Customer < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
	has_many :repairs
	has_many :bicycles
end

app/models/repair.rb
class Repair < ActiveRecord::Base
  belongs_to :bicycle
end

app/controllers/admin/repairs_controller.rb
class Admin::RepairsController < ApplicationController
	before_filter :authenticate_admin!
	
	def index
		@repairs = Repair.where(:is_finished => nil)
		@completed_repairs = Repair.where(:is_finished => true)
	end	


	def edit
		@repair = Repair.find(params[:id])
	end	

	def update
		@repair = Repair.find(params[:id])

		if @repair.update_attributes safe_repair_params.merge(:is_finished => true)
		end
		redirect_to admin_repair_path
	end	

	def show
		@repair = Repair.find(params[:id])
		send_text_message
	end	
  def safe_repair_params
    params.require(:repair).permit(:is_finished, :date_completed, :performed_by, :notes)
  end

  def send_text_message
    number_to_send_to = "3012571389"

    #twilio_sid = ENV["TWILIO_ACCOUNT_SID"]
    #twilio_token = ENV["TWILIO_AUTH_TOKEN"]
    #twilio_phone_number = ENV["TWILIO_PHONE_NUMBER"]
    twilio_sid = "AC8cd6478206bc43d090754e4ecaeeb2ac"
    twilio_token = "e8a290a6070158ba08a060ae9f117215"
    twilio_phone_number = "12406164389"
    message = "Your repair is complete! Please come pick it up."
    @twilio_client = Twilio::REST::Client.new twilio_sid, twilio_token

    @twilio_client.account.sms.messages.create(
      :from => "+1#{twilio_phone_number}",
      :to => number_to_send_to,
      :body => message
    )
  end

end	

app/controllers/admins_controller.rb
class AdminsController < ApplicationController
	before_filter :authenticate_admin!,  except: :index


	def index

	end	
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

	def after_sign_in_path_for(resource)
		if resource.class == Admin
			'/admin/repairs'
		elsif resource.class == Customer
			'/bicycles'	
		end	
  end
  
end

app/controllers/bicycles_controller.rb
class BicyclesController < ApplicationController
	before_filter :authenticate_customer!,  except: :index

	def index
		@bicycles = current_customer.bicycles if current_customer
	end

	def show
    @bicycle = current_customer.bicycles.find(params[:id])

  end

  def new
  	@bicycle = current_customer.bicycles.build
  end

  def create
  	@bicycle = current_customer.bicycles.build safe_bicycle_params
  
    if @bicycle.save
      flash[:notice] = "This Bike was just added to your locker successfully:"
      redirect_to bicycle_path(@bicycle)
    else
      flash.now[:alert] = @bicycle.errors.first
      render 'new'
    end
  end	

  def safe_bicycle_params
    params.require(:bicycle).permit(:manufacturer, :model, :model_year, :serial_number)
  end
end

app/controllers/repairs_controller.rb
class RepairsController < ApplicationController
	before_filter :authenticate_customer!,  except: :index

	def index
		@bicycle = current_customer.bicycles.find(params[:bicycle_id])
  	@repairs = @bicycle.repairs
	end

	def show
    @bicycle = current_customer.bicycles.find(params[:bicycle_id])
  	@repair = @bicycle.repairs.find(params[:id])
  end

  def new
  	@bicycle = current_customer.bicycles.find(params[:bicycle_id])
  	@repair = @bicycle.repairs.build
  end

  def create
  	@bicycle = current_customer.bicycles.find(params[:bicycle_id])
  	@repair = @bicycle.repairs.build safe_repair_params
    if @repair.save
      flash[:notice] = "This repair was just created successfully:"
      redirect_to bicycle_repair_path(@bicycle, @repair)
    else
      flash.now[:alert] = @repair.errors.first
      render 'new'
    end
  end	

  def safe_repair_params
    params.require(:repair).permit(:service_requested, :date_scheduled)
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  	@bicycles = current_customer.bicycles.order('manufacturer DESC')
  end
  	
end

  

app/helpers/admins_helper.rb
module AdminsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/bicycles_helper.rb
module BicyclesHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/admin/repairs/edit.html.erb
<h2>Edit Repair Ticket</h2>
<h4><%= "#{@repair.bicycle.model} - #{@repair.service_requested}" %></h4>

<div class="container">
<%= form_for [:admin, @repair] do |f| %>
  <div class="form-group">
    <%= f.label :date_completed %>
    <%= f.date_select :date_completed, class: 'form-control' %>
  </div>
  <div class="form-group">
    <%= f.label :performed_by %>
    <%= f.text_field :performed_by, class: 'form-control', :style => "width:250px;"  %>
  </div>
  <div class="form-group">
    <%= f.label :notes %>
    <%= f.text_area  :notes, class: 'form-control', rows: "5" %>
  </div>
  
  <br>
  <div>
    <%= f.submit 'Close Repair Ticket', class: 'btn btn-primary btn-lg' %>
  </div>
<% end %>
</div>

app/views/admin/repairs/index.html.erb
<h3>Active Repair Log</h3>
<section>
	<% if defined? @repairs %>
  	<% @repairs.each do |repair| %>
    	<article>
      	<section>
        	<h5><%= link_to "#{repair.bicycle.model} - #{repair.service_requested}", edit_admin_repair_path(repair) %></h5>
        
      	</section>
    	</article>
  	<% end %>
  <% end %>
	
</section>

<h3>Completed Repair Log</h3>
<section>
  <% if defined? @completed_repairs %>
    <% @completed_repairs.each do |completed_repair| %>
      <article>
        <section>
          <h5><%= link_to completed_repair.service_requested, admin_repair_path(completed_repair) %></h5>
        
        </section>
      </article>
    <% end %>
  <% end %>
  
</section>

app/views/admin/repairs/show.html.erb
<h4><%= "#{@repair.bicycle.model} - #{@repair.service_requested}" %></h4>
<h4>Completed by: <%= "#{@repair.performed_by}" %></h4>
<h4>Notes: <%= "#{@repair.notes}" %></h4>
<h4>Completed on: <%= "#{@repair.date_completed}" %></h4>
</br></br>
<h5><%= link_to "Return to repair log", admin_repairs_path %></h5>

app/views/bicycles/index.html.erb
<h1>My Bike Inventory</h1>
<section>
	<% if defined? @bicycles %>
  	<% @bicycles.each do |bicycle| %>
    	<article>
      	<section>
        	<h3><%= link_to bicycle.model, bicycle_path(bicycle) %></h3>
        
      	</section>
    	</article>
  	<% end %>
  <% end %>

  <%= link_to "Add a new bicycle", new_bicycle_path %>
	
</section>

app/views/bicycles/new.html.erb
<h2>Add a bike to your garage</h2>
<div class="container">
<%= form_for @bicycle do |f| %>
  <div class="form-group">
    <%= f.label :manufacturer %>
    <%= f.text_field :manufacturer, class: 'form-control', :style => "width:250px;" %>
  </div>
  <div class="form-group">
    <%= f.label :model %>
    <%= f.text_field :model, class: 'form-control', :style => "width:250px;" %>
  </div>
  <div class="form-group">
    <%= f.label :model_year %>
    <%= f.number_field :model_year, class: 'form-control', :style => "width:250px;" %>
  </div>
  <div class="form-group">
    <%= f.label :serial_number %>
    <%= f.text_field :serial_number, class: 'form-control', :style => "width:250px;" %>
  </div>
  <br>
  <div>
    <%= f.submit 'Create Bike', class: 'btn btn-primary btn-lg' %>
  </div>
<% end %>
</div>

app/views/bicycles/show.html.erb
<h3><%= @bicycle.model %></h3>

<div>
  <p><%= @bicycle.manufacturer %> </p>
  <p><%= @bicycle.model_year %> </p>
  <p><%= @bicycle.serial_number %> </p>

</div>

<%= link_to "Create a new repair ticket", new_bicycle_repair_path(@bicycle) %></br>

<%= link_to "Get the repair history for this bike", bicycle_repairs_path(@bicycle) %></br>

<%= link_to "Return to your bike locker", bicycles_path %></br>

app/views/customers/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
  <%= link_to "Sign up", new_registration_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations' %>
  <%= link_to "Forgot your password?", new_password_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= link_to "Sign in with #{provider.to_s.titleize}", omniauth_authorize_path(resource_name, provider) %><br />
  <% end -%>
<% end -%>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Revolution Cycles Portal</title>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
    <%= csrf_meta_tags %>
  </head>
  <body>
    <nav class="navbar navbar-default">
      <div class="navbar navbar-header">
        <a class="navbar-brand" href="#">Revolution Cycles Bike Locker</a>
      </div>
      <ul class="nav navbar-nav">
        <li><%= link_to "Home", root_path %></li>
        
        <% if customer_signed_in? %>
          <li><%= link_to "Log out", destroy_customer_session_path, method: :delete %></li>
        <% elsif admin_signed_in? %>
          <li><%= link_to "Log out", destroy_admin_session_path, method: :delete %></li>  
        <% else %>
          <li><%= link_to "Sign up", new_customer_registration_path %></li>
          <li><%= link_to "Log in", new_customer_session_path %></li>
        <% end %>
      </ul>
      <%= image_tag("revolution_cycles-va.png", size: "50x50", class: "pull-right") %>
    </nav>
    <p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>

    <%= yield %>
   
  </body>
</html>

app/views/repairs/index.html.erb
<h3>Repair log for <%=@bicycle.manufacturer%> <%=@bicycle.model%></h3>
<ul>
<% @repairs.each do |repair| %>
	<li>
		<p>Service requested: <%= repair.service_requested %> </p>
		<p>Date Scheduled: <%= repair.date_scheduled %> </p>
		<% if repair.date_completed == nil %>
			<p>Pending</p>
			<% else %>
			<p>Date Completed: <%= repair.date_completed %> </p>
			<p>Completed by: <%= repair.performed_by %> </p>
			<p>Notes: <%= repair.notes %> </p>
		<% end %>
	</li>	
	<% end %>
</ul>
</br>
<%= link_to "Return to your bike locker", bicycles_path %>

app/views/repairs/new.html.erb
<h2>Add a repair for your bicycle</h2>
<div class="container">
<%= form_for [@bicycle, @repair] do |f| %>
  <div class="form-group">
    <%= f.label :service_requested%>
    <%= f.select :service_requested, options_for_select(["Complete Over Haul", "Basic Tune Up", "Warranty Tune Up", "Wheel Build", "Front Flat Repair", "Rear Flat Repair"]), class: 'form-control'%>
  </div>
  <div class="form-group">
    <%= f.label :date_scheduled %>
    <%= f.date_select :date_scheduled, class: 'form-control' %>
  </div>
  
  <br>
  <div>
    <%= f.submit 'Create Repair', class: 'btn btn-primary btn-lg' %>
  </div>
<% end %>
</div>

app/views/repairs/show.html.erb
<h3><%= @repair.service_requested %></h3>
To be submitted for service on:</br>
<%= @repair.date_scheduled %>
</br>

<%= link_to "Return to your bike locker", bicycles_path %></br>